repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: check-merge-conflict
      - id: check-toml
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--ignore", "E501,E203,W503,E501", "--max-line-length", "88"]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==23.3.0]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
      - id: nbqa-flake8
        additional_dependencies: [flake8==5.0.4]
      - id: nbqa-isort
        additional_dependencies: [isort==5.11.5]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
